[reader]
# This section allows common NFC readers to be used.
nfc_enabled = true

# Set to the COM port number of the reader. Set to 0 to auto detect. Auto 
# detection is not guaranteed to work and may cause the program to freeze on
# startup, in which case the actual port number must be provided.
com_port = 0

# Set to the NFC chipset of the reader. nfcpy currently supports these drivers:
# rcs380, pn531, pn532, pn533, rcs956, acr122
driver = "pn532"

# If the tag is removed, wait this many seconds before executing the exit
# command. If the tag is replaced within this time, reset the timer.
remove_timeout = 3

# Set to true to write the IDs of scanned tags not in the tag_commands list
# to new_tags.txt as they are scanned. If this file cannot be written, the
# IDs will be written to the console before exiting.
log_new_tags = true

# Set to true to launch a pseudorandom command when a scanned tag is not
# defined in the tag_commands. A hash is calculated from the tag's ID and
# matched to a command in numeric order, such that the same foreign tag will
# always launch the same command for a given list of commands. The tag's ID
# will still be logged if log_new_tags is true.
launch_pseudorandom_command_on_new_tag = false

[tag_commands]
# Add keys that match NFC tag IDs with values that contain the command to run.
# Relative paths resolve to the "programs" subdirectory where main.py is run.
# Comments can be added to identify specific IDs.
0000000000 = "sample1.bat" # Sample card line
ffffffffff = "sample2.bat" # Different sample card

[button]
# This section allows a keyboard key to launch a random command.
button_enabled = true

# A keyboard key that will be used as a shortcut to immediately execute a 
# random command, and later exit that command.
# Use a single character, or see the pynput documentation for key codes:
# https://pynput.readthedocs.io/en/latest/keyboard.html#pynput.keyboard.Key
key = "f16"

# Button command list mode, one of "whitelist" or "blacklist".
# If whitelist mode is enabled, only the commands in the whitelist_commands 
# will be used. This can be used to allow different commands from the NFC tags.
# If blacklist mode is enabled, all tag_commands will be used (ignoring tag 
# IDs) except for commands that match the blacklist_commands. This can be used 
# to allow all commands except those used for administration or maintenance.
# The default is "blacklist".
button_mode = "blacklist"

whitelist_commands = [
    "command1.bat",
    "command2.bat",
    "command3.bat",
]

blacklist_commands = [
    "override.bat",
    "shutdown.bat",
]

# If button_mode is blacklist, these commands will be added to the list of
# commands available with the button press after filtering.
extra_commands = [
]

# Attempt to pick unique commands by maintaining a history of previously
# launched commands, limited to this number of commands. Before launching
# a randomly selected command, the history is scanned for the same command.
# If the command is in the history, another randomly selected command will
# be tried, up to the number of retries set below, after which the next
# random command is launched unconditionally.
# The text file button_commands_history.txt is used for this history. It will
# be created if it does not exist.
# Set button_commands_history to 0 to disable.
button_commands_history = 50
button_commands_random_retries = 10

# The Scroll Lock light can be used to indicate if a command can be launched 
# with the button. It will turn on when no command is active and turn off
# when the button is pressed, as the command launches. It will also turn off
# when a NFC tag is used to launch a command to indicate that the button is
# temporarily disabled, until the tag is removed.
# Enabling this is not recommended if any programs you run depend on the status
# of Scroll Lock.
button_use_scroll_lock = false